#!/bin/bash

#The MIT License (MIT)
#
#Copyright (c) <2016> <edgar.a.ramos.rambaud@gmail.com>
#
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

if [[ $# != 4 ]];
then    
    echo "Usage: pem2jks CERT_FILE KEY_FILE ALIAS JKS_FILE"
    exit 1
fi

cerfile=$1
keyfile=$2
alias=$3
outfile=$4

openssl pkcs12 -export -inkey $keyfile -in $cerfile -name $alias -out tmp.p12

keytool -importkeystore -srckeystore tmp.p12 -srcstoretype PKCS12 -destkeystore $outfile -deststoretype JKS

rm tmp.p12

exit 0
